// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_cY_3MGbrfaHuwr_mtVfW3fmor8I3ees',
    appId: '1:665358255541:android:a1f1302d8a0911731ac5fc',
    messagingSenderId: '665358255541',
    projectId: 'login-auth-flutter-64673',
    storageBucket: 'login-auth-flutter-64673.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAICQ-nUWCBW6C6oGpmGb1uFcGL6cJg8Q0',
    appId: '1:665358255541:ios:af529c2ceb6d2e701ac5fc',
    messagingSenderId: '665358255541',
    projectId: 'login-auth-flutter-64673',
    storageBucket: 'login-auth-flutter-64673.firebasestorage.app',
    androidClientId: '665358255541-nb6uur1at7jpbtnr6h5p6svt3i2mh7pb.apps.googleusercontent.com',
    iosClientId: '665358255541-80am6a01t4ci93duim6relvt62k463j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterZth',
  );

}